### ISSUE TITLE
Define a class Account with attributes such as:  ■ Account number  ■ PIN  ■ Balance

### ISSUE THREAD

**Issue by Mohammed159159** [Mohammed159159/ATM-Machine-Simulation-in-CPP#1]

**Comment by MeenaMaged** [comment]
class Account {
private:
    long accountNum;
    int pin;
    long balance;

public:
    Account(long AccountNum, int Pin, long Balance) {
        accountNum = AccountNum;
        pin = Pin;
        balance = Balance;
    }
