### ISSUE TITLE
Create Menu Interface

### ISSUE THREAD

**Issue by Mohammed159159** [Mohammed159159/ATM-Machine-Simulation-in-CPP#7]
Once logged in, display a menu with the following options:
 1. Check Balance
 2. Deposit Money
 3. Withdraw Money
 4. Change PIN
 5. Exit

**Comment by MeenaMaged** [comment]
// show login menu
        cout << "Login successful." << endl;

        string menuFunctions[5] = { "Check Balance", "Deposit Money", "Withdraw Money", "Change PIN", "Exit" };
        for (int i = 0; i < 5; i++)
        {
            cout << i + 1 << ". " << menuFunctions[i] << endl;
        }
